name = "status-axolotlpower-com"
main = "src/index.js"
compatibility_date = "2024-01-17"
node_compat = true

[placement]
mode = "smart"

[[kv_namespaces]]
binding = "STATUS_INFO"
id = "b9054efdd25d46cfb8bc8b805f9816c0"

[triggers]
crons = ["*/2 * * * *"]
